config/routes.rb
Nodalpoint::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/login" => "sessions#index", :as => "login"

  match "/typeahead/brand" => "users#users_brands", :as => "brand_typeahead"

  resources :cameras
  resources :lenses
  resources :nodal_points

  resources :users

  root :to => 'nodal_points#index'
end

app/controllers/lenses_controller.rb
class LensesController < AuthenticatedController
  before_filter :find_lens, :only => [:show, :edit, :update, :destroy]

  def index
    @lenses = current_user.lenses.ordered
  end

  def new
    @lens = Lens.new
    @lens.user = current_user
  end

  def create
    @lens = Lens.new(params[:lens])
    @lens.user = current_user

    if @lens.save
      redirect_to lenses_url, notice: t('lens.create.ok')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    if @lens.update_attributes(params[:lens])
      redirect_to lenses_url, notice: t('lens.update.ok')
    else
      render :action => "edit"
    end
  end

  def destroy
    if @lens.deletable?
      @lens.destroy

      redirect_to lenses_url, notice: t('lens.delete.ok')
    else
      redirect_to lenses_url, notice: t('lens.delete.in.use')
    end

  end


  private

  def find_lens
    @lens = current_user.lenses.find(params[:id])
  end
end

app/views/lenses/_form.html.haml
= simple_form_for lens, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend= legend

    = f.input :name
    = f.input :brand, input_html: { :class => 'brand-typeahead', :data => { 'typeahead-link' => brand_typeahead_url } }
    = f.input :minimum_focal_length
    = f.input :maximum_focal_length

    %div.form-actions
      = f.button :submit, :class => 'btn-primary'
      = link_to t("form.button.cancel"), :back, :class => 'btn'

app/views/lenses/edit.html.haml
= render :partial => 'form', :locals => { :lens => @lens, :legend => t('lens.form.legend.edit') }

app/views/lenses/index.html.haml
.well
  %i.icon-plus
  = link_to t('lens.button.add'), new_lens_path

%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= "Name"
      %th= "Brand"
      %th= "Focal Range"
      %th= "Actions"

  %tbody
    - @lenses.each do |lens|
      %tr
        %td= lens.name
        %td= lens.brand
        %td= lens.focal_range
        %td
          = link_to raw("<i class='icon-eye-open'></i>"), lens_path(lens), :class => 'btn btn-mini', :title => "Show #{lens.name}"
          = link_to raw("<i class='icon-edit'></i>"), edit_lens_path(lens), :class => 'btn btn-mini btn-warning', :title => "Edit #{lens.name}"
          - if lens.deletable?
            = link_to raw("<i class='icon-trash'></i>"), lens_path(lens), :method => 'delete', :confirm => "Sure?", :class => 'btn btn-mini btn-danger', :title => "Delete #{lens.name}", :class => 'btn btn-mini btn-danger'

app/views/lenses/new.html.haml
= render :partial => 'form', :locals => { :lens => @lens, :legend => t('lens.form.legend.new') }

app/views/lenses/show.html.haml
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= t('lens.list.field')
      %th= t('lens.list.val')

  %tbody
    %tr
      %td= t('lens.field.name')
      %td= @lens.name
    %tr
      %td= t('lens.field.brand')
      %td= @lens.brand
    %tr
      %td= t('lens.field.frange')
      %td= @lens.focal_range

%div.well
  = link_to t('lens.list.back'), lenses_path, :class => 'btn btn-default'
  = link_to t('button.edit'), edit_lens_path(@lens), :class => 'btn btn-warning'
  - if @lens.deletable?
    = link_to t('button.delete'), lens_path(@lens), :method => 'delete', :confirm => t('show.delete.confirm'), :class => 'btn btn-danger'