config/routes.rb
Nodalpoint::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/login" => "sessions#index", :as => "login"

  match "/typeahead/brand" => "users#users_brands", :as => "brand_typeahead"

  resources :cameras
  resources :lenses
  resources :nodal_points

  resources :users

  root :to => 'nodal_points#index'
end

app/models/nodal_point.rb
class NodalPoint < ActiveRecord::Base
  attr_accessible :focal_length, :offset, :camera_id, :lens_id

  belongs_to :lens
  belongs_to :camera

  belongs_to :user

  delegate :name,  :to => :camera, :prefix => true, :allow_nil => true
  delegate :brand, :to => :camera, :prefix => true, :allow_nil => true
  delegate :name,  :to => :lens,   :prefix => true, :allow_nil => true
  delegate :brand, :to => :lens,   :prefix => true, :allow_nil => true

  scope :preloaded, :include => [:camera, :lens]

  validates_presence_of :offset, :focal_length, :camera, :lens
  validates_numericality_of :offset, :focal_length
  validate :camera_owned_by_me
  validate :lens_owned_by_me
  validate :focal_length_suits_lens

  def self.ordered
    NodalPoint.order('cameras.name ASC, lenses.name ASC, focal_length ASC').joins(:camera).joins(:lens).preloaded
  end

  private

  def lens_owned_by_me
    if self.lens
      unless self.user == self.lens.user
        errors.add(:lens, I18n.t('nodal_point.errors.lens.owner'))
      end
    end
  end

  def camera_owned_by_me
    if self.camera
      unless self.user == self.camera.user
        errors.add(:camera, I18n.t('nodal_point.errors.camera.owner'))
      end
    end
  end

  def focal_length_suits_lens
    if self.lens && !self.focal_length.blank?
      if self.lens.minimum_focal_length > self.focal_length || self.lens.maximum_focal_length < self.focal_length
        errors.add(:focal_length, I18n.t('nodal_point.errors.lens.range', :min => self.lens.minimum_focal_length, :max => self.lens.maximum_focal_length))
      end
    end
  end
end

app/controllers/nodal_points_controller.rb
class NodalPointsController < AuthenticatedController
  before_filter :find_nodal_point, :only => [:show, :edit, :update, :destroy]

  def index
    @nodal_points = current_user.nodal_points.ordered
  end

  def new
    @nodal_point = NodalPoint.new
    @nodal_point.user = current_user
  end

  def create
     @nodal_point = NodalPoint.new(params[:nodal_point])
     @nodal_point.user = current_user

     if @nodal_point.save
       redirect_to nodal_points_url, notice: t('nodal_point.create.ok')
     else
       render :action => "new"
     end
   end

   def edit
   end

   def show
   end

   def update
     if @nodal_point.update_attributes(params[:nodal_point])
       redirect_to nodal_points_url, notice: t('nodal_point.update.ok')
     else
       render :action => "edit"
     end
   end

   def destroy
     @nodal_point.destroy

     redirect_to nodal_points_url, notice: t('nodal_point.delete.ok')
   end


  private

  def find_nodal_point
    @nodal_point = current_user.nodal_points.find(params[:id])
  end
end

app/views/nodal_points/_form.html.haml
= simple_form_for nodal_point, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend= legend

    = f.association :camera, :collection => nodal_point.user.cameras.ordered, :label_method => lambda { |c| "#{c.name} (#{c.brand})" }, :include_blank => false
    %div.control-group.select.required
      %label.select.required.control-label{ :for => 'nodal_point_lens_id'}
        %abbr{ :title => "required"}= "*"
        Lens
      %div.controls
        = f.association :lens do
          = f.select :lens_id, nodal_point.user.lenses.ordered.map{|l| ["#{l.name} (#{l.brand})", l.id, {"data-min" => l.minimum_focal_length, "data-max" => l.maximum_focal_length}]}
    = f.input :focal_length, input_html: focal_length_html_attributes_for_lens(nodal_point.user.lenses.ordered.first, nodal_point.focal_length)
    = f.input :offset

    %div.form-actions
      = f.button :submit, :class => 'btn-primary'
      = link_to t("form.button.cancel"), :back, :class => 'btn'

app/views/nodal_points/edit.html.haml
= render :partial => 'form', :locals => { :nodal_point => @nodal_point, :legend => t('nodal_point.form.legend.edit') }

app/views/nodal_points/index.html.haml
.well
  - if current_user.lenses.size > 0 && current_user.cameras.size > 0
    %i.icon-plus= link_to t('nodal_point.button.add'), new_nodal_point_path
  - else
    %p= t('nodal_point.requirements')

%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= t('nodal_point.list.camera')
      %th= t('nodal_point.list.lens')
      %th= t('nodal_point.list.focal_length')
      %th= t('nodal_point.list.offset')
      %th= "Actions"

  %tbody
    - @nodal_points.each do |nodal_point|
      %tr
        %td= "#{nodal_point.camera_name} (#{nodal_point.camera_brand})"
        %td= "#{nodal_point.lens_name} (#{nodal_point.lens_brand})"
        %td= nodal_point.focal_length
        %td= nodal_point.offset
        %td
          = link_to raw("<i class='icon-eye-open'></i>"), nodal_point_path(nodal_point), :class => 'btn btn-mini', :title => "Show"
          = link_to raw("<i class='icon-edit'></i>"), edit_nodal_point_path(nodal_point), :class => 'btn btn-mini btn-warning', :title => "Edit"
          = link_to raw("<i class='icon-trash'></i>"), nodal_point_path(nodal_point), :method => 'delete', :confirm => "Sure?", :class => 'btn btn-mini btn-danger', :title => "Delete"

app/views/nodal_points/new.html.haml
= render :partial => 'form', :locals => { :nodal_point => @nodal_point, :legend => t('nodal_point.form.legend.new') }

app/views/nodal_points/show.html.haml
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= t('nodal_point.list.field')
      %th= t('nodal_point.list.val')

  %tbody
    %tr
      %td= t('nodal_point.field.camera')
      %td= @nodal_point.camera_name (@nodal_point.camera_brand)
    %tr
      %td= t('nodal_point.field.lens')
      %td= @nodal_point.lens_name (@nodal_point.lens_brand)
    %tr
      %td= t('nodal_point.field.focal_length')
      %td= @nodal_point.focal_length
    %tr
      %td= t('nodal_point.field.offset')
      %td= @nodal_point.offset


%div.well
  = link_to t('nodal_point.list.back'), nodal_points_path, :class => 'btn btn-default'
  = link_to t('button.edit'), edit_nodal_point_path(@nodal_point), :class => 'btn btn-warning'
  = link_to t('button.delete'), nodal_point_path(@nodal_point), :method => 'delete', :confirm => t('show.delete.confirm'), :class => 'btn btn-danger'