config/routes.rb
Nodalpoint::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/login" => "sessions#index", :as => "login"

  match "/typeahead/brand" => "users#users_brands", :as => "brand_typeahead"

  resources :cameras
  resources :lenses
  resources :nodal_points

  resources :users

  root :to => 'nodal_points#index'
end

app/models/camera.rb
class Camera < ActiveRecord::Base
  attr_accessible :brand, :name

  has_many :nodal_points

  belongs_to :user

  scope :ordered, :order => 'name ASC, brand ASC'

  validates_presence_of :name, :brand

  def deletable?
    nodal_points.size() == 0
  end
end

app/controllers/cameras_controller.rb
class CamerasController < AuthenticatedController
  before_filter :find_camera, :only => [:show, :edit, :update, :destroy]

  def index
    @cameras = current_user.cameras.ordered
  end

  def new
    @camera = Camera.new
    @camera.user = current_user
  end

  def create
    @camera = Camera.new(params[:camera])
    @camera.user = current_user

    if @camera.save
      redirect_to cameras_url, notice: t('camera.create.ok')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    if @camera.update_attributes(params[:camera])
      redirect_to cameras_url, notice: t('camera.update.ok')
    else
      render :action => "edit"
    end
  end

  def destroy
    if @camera.deletable?
      @camera.destroy

      redirect_to cameras_url, notice: t('camera.delete.ok')
    else
      redirect_to cameras_url, notice: t('camera.delete.in.use')
    end
  end


  private

  def find_camera
    @camera = current_user.cameras.find(params[:id])
  end
end

app/views/cameras/_form.html.haml
= simple_form_for camera, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend= legend

    = f.input :name
    = f.input :brand, input_html: { :class => 'brand-typeahead', :data => { 'typeahead-link' => brand_typeahead_url } }

    %div.form-actions
      = f.button :submit, :class => 'btn-primary'
      = link_to t("form.button.cancel"), :back, :class => 'btn'

app/views/cameras/edit.html.haml
= render :partial => 'form', :locals => { :camera => @camera, :legend => t('camera.form.legend.edit') }

app/views/cameras/index.html.haml
.well
  %i.icon-plus
  = link_to t('camera.button.add'), new_camera_path

%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= "Name"
      %th= "Brand"
      %th= "Actions"

  %tbody
    - @cameras.each do |camera|
      %tr
        %td= camera.name
        %td= camera.brand
        %td
          = link_to raw("<i class='icon-eye-open'></i>"), camera_path(camera), :class => 'btn btn-mini', :title => "Show #{camera.name}"
          = link_to raw("<i class='icon-edit'></i>"), edit_camera_path(camera), :class => 'btn btn-mini btn-warning', :title => "Edit #{camera.name}"
          - if camera.deletable?
            = link_to raw("<i class='icon-trash'></i>"), camera_path(camera), :method => 'delete', :confirm => "Sure?", :class => 'btn btn-mini btn-danger', :title => "Delete #{camera.name}", :class => 'btn btn-mini btn-danger'

app/views/cameras/new.html.haml
= render :partial => 'form', :locals => { :camera => @camera, :legend => t('camera.form.legend.new') }

app/views/cameras/show.html.haml
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= t('camera.list.field')
      %th= t('camera.list.val')

  %tbody
    %tr
      %td= t('camera.field.name')
      %td= @camera.name
    %tr
      %td= t('camera.field.brand')
      %td= @camera.brand

%div.well
  = link_to t('camera.list.back'), cameras_path, :class => 'btn btn-default'
  = link_to t('button.edit'), edit_camera_path(@camera), :class => 'btn btn-warning'
  - if @camera.deletable?
    = link_to t('button.delete'), camera_path(@camera), :method => 'delete', :confirm => t('show.delete.confirm'), :class => 'btn btn-danger'