config/routes.rb
Nodalpoint::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/login" => "sessions#index", :as => "login"

  match "/typeahead/brand" => "users#users_brands", :as => "brand_typeahead"

  resources :cameras
  resources :lenses
  resources :nodal_points

  resources :users

  root :to => 'nodal_points#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_current_user

  helper_method :current_user

  def current_user
    @current_user if defined?(@current_user)
  end

  private

  def get_current_user
    if session.has_key? :user_id
      @current_user = User.get_user(session[:user_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.haml
%footer.footer
  %div.container
    %p= t('footer.text').html_safe
    %ul.footer-links
      %li= link_to t('footer.github'), "https://github.com/chrissearle/nodalpoint/"
      %li.muted= "·"
      %li= link_to t('footer.name'), "http://github.com/chrissearle/"

app/views/application/_messages.html.haml
- flash.each do |type, message|
  %div.alert.fade.in{ :'data-alert' => "alert", :class => "alert-#{bootstrap_type(type)}" }
    %a.close{ :href => "#", :'data-dismiss' => "alert" } ×
    %p
      = message

app/views/application/_navbar_left_menu.html.haml
%ul.nav
  %li= link_to t('nodal_point.items'), nodal_points_path
  %li= link_to t('camera.items'), cameras_path
  %li= link_to t('lens.items'), lenses_path

app/views/application/_navbar_right_menu.html.haml
%ul.nav.pull-right
  - if current_user
    %li.divider-vertical
    = render :partial => 'navbar_right_menu_account'
    %li.divider-vertical
    %li= link_to t('menu.logout'), logout_path
  - else
    %li= link_to t('menu.login'), login_path

app/views/application/_navbar_right_menu_account.html.haml
%li.dropdown
  %a.dropdown-toggle{ :href => "#", :'data-toggle' => "dropdown" }
    = link_with_icon( 'icon-user', t('menu.dropdown.account'), true)
    %b.caret
  %ul.dropdown-menu
    %li= link_to t('sidenav.link.profile'), login_path
    %li= link_to t('sidenav.link.logout'), logout_path

app/views/application/_navigation.html.haml
%div.navbar.navbar-fixed-top.navbar-inverse
  %div.navbar-inner
    %div.container
      %a.btn.btn-navbar{ :'data-toggle' => "collapse", :'data-target' => ".nav-collapse" }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to link_with_icon("icon-camera", t('site.brand')), root_path, :class => 'brand'
      %div.nav-collapse
        = render :partial => 'navbar_left_menu'
        = render :partial => 'navbar_search_form'
        = render :partial => 'navbar_right_menu'